### ISSUE TITLE
Syncing initial state

### ISSUE THREAD

**Issue by thdxr** [lasp-lang/lasp_pg#13]
Given the following order of events

- Server 1 starts up
- Server 1 adds Process 1 to a `lasp_pg` group
- Server 2 starts up
- Server 2 joins as peer

At this point Server 2 does not have the latest registrations.  Is this supposed to be handler by the library or is it something I need to implement myself?

**Comment by ZGF4** [comment]
Seems to have fixed itself after setting `partisan_default_peer_service_manager` explicitly,

**Comment by cmeiklejohn** [comment]
`partisan_default_peer_service_manager` is the default manager.

Server 2 shouldn't get the registrations until the first anti-entropy interval is fired -- which is performed periodically, at a configurable interval.

**Comment by thdxr** [comment]
What is the default for that?

**Comment by vitorenesduarte** [comment]
It seems it's 10s:
https://github.com/lasp-lang/lasp/blob/master/src/lasp_sup.erl#L329

**Comment by tsloughter** [comment]
Could it be triggered to happen immediately after start? Would be nice to not have to have a small anti-entropy interval just to get it to trigger earlier after start.

**Comment by tsloughter** [comment]
There should probably be a notice in the docs or readme that the user likely wants to at least lower the default `delta_interval`, since that one is 10 seconds.

**Comment by cmeiklejohn** [comment]
Moved to https://github.com/lasp-lang/lasp/issues/290.
