### ISSUE TITLE
Unneeded dependencies?

### ISSUE THREAD

**Issue by tsloughter** [lasp-lang/lasp_pg#2]
Ranch and mochiweb are listed in the `.app.src` applications list. But they don't appear to be needed, can they be removed?

**Comment by cmeiklejohn** [comment]
I only saw mochiweb, not ranch.  But, I'll open a PR to remove it.

**Comment by tsloughter** [comment]
Ranch is listed as an included_dependency for some reason: https://github.com/lasp-lang/lasp_pg/blob/master/src/lasp_pg.app.src#L6

**Comment by cmeiklejohn** [comment]
I think you should just be able to open a PR to remove the unnecessary
dependency. I do not believe that it is needed at all.
