### ISSUE TITLE
Cannot build release

### ISSUE THREAD

**Issue by tsloughter** [lasp-lang/lasp_pg#8]
In order to be able to build a release lasp and lasp_pg can not both have `partisan` as an `included_application`.

**Comment by cmeiklejohn** [comment]
Oh wait, Lasp PG doesn't need Partisan as an included application, only
Lasp. I think that should resolve the problem, right?

**Comment by tsloughter** [comment]
As long as lasp_pg doesn't try to start it, yes. That would resolve #7 as well.
